// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfgnILYwRbR9TZo22KZ_1PL3i2_5imi3Y',
    appId: '1:316126422536:web:268a2b33b16dd8e6db53bd',
    messagingSenderId: '316126422536',
    projectId: 'app-vacunacion-formosa',
    authDomain: 'app-vacunacion-formosa.firebaseapp.com',
    storageBucket: 'app-vacunacion-formosa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-SzBEStcJ6fPoNSURxLz1vlOEJ-pz-ho',
    appId: '1:316126422536:android:4c48108277ad366adb53bd',
    messagingSenderId: '316126422536',
    projectId: 'app-vacunacion-formosa',
    storageBucket: 'app-vacunacion-formosa.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhewqZDSY8-AySX3zJ1MWVQWWAijeI6h8',
    appId: '1:316126422536:ios:dcaf992cdefb35a2db53bd',
    messagingSenderId: '316126422536',
    projectId: 'app-vacunacion-formosa',
    storageBucket: 'app-vacunacion-formosa.firebasestorage.app',
    iosBundleId: 'ar.gob.formosa.vacunacion',
  );
}
